#########################
## Basic Configuration ##
#########################

api_key:

## @param hostname - string - optional - default: auto-detected
## @env DD_HOSTNAME - string - optional - default: auto-detected
## Force the hostname name.
hostname: <HOSTNAME_NAME>

## Learn more about tagging: https://docs.datadoghq.com/tagging/
# tags:
#   - team:infra
#   - <TAG_KEY>:<TAG_VALUE>

## The environment name where the agent is running. Attached in-app to every
## metric, event, log, trace, and service check emitted by this Agent.
#
# env: <environment name>

##################################
## Log collection Configuration ##
##################################

## Enable Datadog Agent log collection by setting logs_enabled to true.
logs_enabled: true


## Enable container log collection for all the containers (see ac_exclude to filter out containers)
logs_config:
  container_collect_all: true

####################################
## Trace Collection Configuration ##
####################################

## Enter specific configurations for your trace collection.
## See https://docs.datadoghq.com/agent/apm/
apm_config:
  enabled: true

  ## @param env - string - optional - default: none
  ## @env DD_APM_ENV - string - optional - default: none
  ## The environment tag that Traces should be tagged with.
  ## If not set the value will be inherited, in order, from the top level
  ## "env" config option if set and then from the 'env:' tag if present in the
  ## 'tags' top level config option.
  #
  # env: none

  ## @param receiver_port - integer - optional - default: 8126
  ## @env DD_APM_RECEIVER_PORT - integer - optional - default: 8126
  ## The port that the trace receiver should listen on.
  ## Set to 0 to disable the HTTP receiver.
  #
  # receiver_port: 8126

  ## @param log_file - string - optional
  ## @env DD_APM_LOG_FILE - string - optional
  ## The full path to the file where APM-agent logs are written.
  #
  # log_file: <APM_LOG_FILE_PATH>

  ## @param instrumentation_enabled - boolean - default: false
  ## @env DD_APM_INSTRUMENTATION_ENABLED - boolean - default: false
  ## Enables Single Step Instrumentation in the cluster (in beta)
  #
  # instrumentation_enabled: false

######################################
## Process Collection Configuration ##
######################################


See https://docs.datadoghq.com/graphing/infrastructure/process/

process_config:
  process_collection:
    ## Enables collection of information about running processes.
    enabled: false
  container_collection:
    ## Enables collection of information about running containers.
    enabled: true
    
  ## The full path to the file where process Agent logs are written.
  #
  # log_file: <PROCESS_LOG_FILE_PATH>

  process_discovery:
      ## @param enabled - boolean - optional - default: true
      ## Toggles the `process_discovery` check. If enabled, this check gathers information about running integrations.
      enabled: true
###########################################
## Container Autodiscovery Configuration ##
###########################################

## @param container_cgroup_root - string - optional - default: /host/sys/fs/cgroup/
## @env DD_CONTAINER_CGROUP_ROOT - string - optional - default: /host/sys/fs/cgroup/
## Change the root directory to look at to get cgroup statistics.
## Default if environment variable "DOCKER_DD_AGENT" is set to "/host/sys/fs/cgroup"
## and "/sys/fs/cgroup" if not.
#
# container_cgroup_root: /host/sys/fs/cgroup/

## @param container_proc_root - string - optional - default: /host/proc
## @env DD_CONTAINER_PROC_ROOT - string - optional - default: /host/proc
## Change the root directory to look at to get proc statistics.
## Default if environment variable "DOCKER_DD_AGENT" is set "/host/proc" and "/proc" if not.
#
# container_proc_root: /host/proc

## @param listeners - list of key:value elements - optional
## @env DD_LISTENERS - list of key:value elements - optional
## Choose "auto" if you want to let the Agent find any relevant listener on your host
## At the moment, the only auto listener supported is Docker
## If you have already set Docker anywhere in the listeners, the auto listener is ignored
#
# listeners:
#   - name: auto
#   - name: docker

## @param extra_listeners - list of strings - optional
## @env DD_EXTRA_LISTENERS - space separated list of strings - optional
## You can also add additional listeners by name using their default settings.
## This list is available as an environment variable binding.
#
# extra_listeners:
#   - kubelet

## @param ac_exclude - list of comma separated strings - optional
## @env DD_AC_EXCLUDE - list of space separated strings - optional
## Exclude containers from metrics and AD based on their name or image.
## If a container matches an exclude rule, it won't be included unless it first matches an include rule.
## An excluded container won't get any individual container metric reported for it.
## See: https://docs.datadoghq.com/agent/guide/autodiscovery-management/
#
# ac_exclude: []

## @param ac_include - list of comma separated strings - optional
## @env DD_AC_INCLUDE - list of space separated strings - optional
## Include containers from metrics and AD based on their name or image:
## See: https://docs.datadoghq.com/agent/guide/autodiscovery-management/
#
# ac_include: []

#################################
## Cluster Agent Configuration ##
#################################

## @param cluster_agent - custom object - optional
## Settings for the Cluster Agent.
## See https://docs.datadoghq.com/agent/cluster_agent/
#
# cluster_agent:

  ## @param enabled - boolean - optional - default: false
  ## Set to true to enable the Cluster Agent.
  #
  # enabled: false

  ## @param auth_token - string - optional - default: ""
  ## Auth token used to make requests to the Kubernetes API server.
  #
  # auth_token: ""

  ## @param url - string - optional - default: ""
  ## The Cluster Agent endpoint. There's no need to set it if "kubernetes_service_name" is set.
  #
  # url: ""

  ## @param kubernetes_service_name - string - optional - default: "datadog-cluster-agent"
  ## Name of the Kubernetes service for the Cluster Agent.
  #
  # kubernetes_service_name: "datadog-cluster-agent"

#################################
## Cluster check Configuration ##
#################################

## @param cluster_checks - custom object - optional
## Enter specific configurations for your cluster check.
## The cluster-agent is able to autodiscover cluster resources and dispatch checks on
## the node-agents (provided the clustercheck config provider is enabled on them).
## Uncomment this parameter and the one below to enable them.
## See https://docs.datadoghq.com/agent/kubernetes/cluster/
#
# cluster_checks:

  ## @param enabled - boolean - optional - default: false
  ## @env DD_CLUSTER_CHECKS_ENABLED - boolean - optional - default: false
  ## Set to true to enable the dispatching logic on the leader cluster-agent.
  #
  # enabled: false
